const AppTheme = {
  light: {
    section: '#fff',
    maincontainer: '#eee',
    text: '#000',
    tile: '#EFF6FF',
    PrimaryBg: '#004CAC',
    themeColor: '#004CAC',
    lightPrimaryBg: '#EFF6FF',
    whiteBg: '#fff',
    fadedText: '#777',
    mapTheme: [],
    overlayBackground:'#fff',


    Primary: '#004CAC',
    backgroundPrimary: '#d9eafa',
    Secondary: '#303030',
    bgSecondary: '#f6f6f6',
    Tertiary: '#b794f6',
    backgroundTertiary: '#f1e8f6',
    Success: '#008000',
    CreditPoint: '#4caf50',
    Warning: '#FFA200',
    backgroundWarning: '#fcf4e6',
    Yellow: '#fae102',
    Danger: '#fc141f',
    Dark: '#262525',
    Black: '#000000',
    textBlack: '#626B77',
    Medium: '#a6a6a6',
    Progress: '#00c7b5',
    Light: '#fff',
    AppBgColor: '#f8f8f8',
    Snow: '#f9f9f9',
    Blue: '#0061a5',
    TextBlue: '#0092FF',
    LightGrey: '#b5b5b5',
    Lightest: '#c7c7c7',
    SpringBud: '#ABFF00',
    LinkClr: '#3f78f0',
    LinkBlue: '#d4e9ff',
    statusBar: '#dce4e6',
    LightSkyBlue: '#e8f2ff',
    CancelRed: '#EB3B3B',
    GradiantLightRed: '#f52a2a',
    GradiantDarkRed: '#ff0808',
    GradiantLightGreen: '#63c76f',
    GradiantDarkGreen: '#52a85b',
    borderColor: '#ccc',
    Green: '#23CE6B',
    backgroundGreen: '#e8f6ee',
    lightBorderColor: '#d8d8d8',
    TextColor: '#000',
    White: '#fff',
    buttonColor: '#004BAC',
    DeleteBackground: '#FFEFEF',
    DeleteContent: '#D50D2D',
    AlertBackground: '#fff',
    AlertContent: '#FF9F00',
    SubmitBackground: '#78BDF6',
    SubmitContent: '#004BAC',
    SuccessBackground: '#E2FFE7',
    SuccessContent: '#43BF57',
    SoftPurpel: '#8870ff',
    Scanned: '#00c075',
    PendingBg: '#f4c8c8',
    Pending: '#ff7600',
    Reject: '#ff0000',
    BadgeSection: '#FF8886',
    primary100: '#eaddff',
    error50: '#dc362e',
  },
  dark: {
    section: '#1E1E1E',
    maincontainer: '#121212',
    text: '#fff',
    tile: '#0D1B2A',
    PrimaryBg: '#000',
    themeColor: '#004CAC',
    lightPrimaryBg: '#0F172A',
    whiteBg: '#000',
    fadedText: '#aaa',
    overlayBackground:'#000',
    mapTheme: [
  { elementType: 'geometry', stylers: [{ color: '#212121' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#757575' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#212121' }] },
  {
    featureType: 'administrative',
    elementType: 'geometry',
    stylers: [{ color: '#757575' }],
  },
  {
    featureType: 'administrative.country',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#9e9e9e' }],
  },
  {
    featureType: 'administrative.land_parcel',
    stylers: [{ visibility: 'off' }],
  },
  {
    featureType: 'administrative.locality',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#bdbdbd' }],
  },
  {
    featureType: 'poi',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#757575' }],
  },
  {
    featureType: 'poi.park',
    elementType: 'geometry',
    stylers: [{ color: '#181818' }],
  },
  {
    featureType: 'poi.park',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#616161' }],
  },
  {
    featureType: 'poi.park',
    elementType: 'labels.text.stroke',
    stylers: [{ color: '#1b1b1b' }],
  },
  {
    featureType: 'road',
    elementType: 'geometry.fill',
    stylers: [{ color: '#2c2c2c' }],
  },
  {
    featureType: 'road',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#8a8a8a' }],
  },
  {
    featureType: 'road.arterial',
    elementType: 'geometry',
    stylers: [{ color: '#373737' }],
  },
  {
    featureType: 'road.highway',
    elementType: 'geometry',
    stylers: [{ color: '#3c3c3c' }],
  },
  {
    featureType: 'road.highway.controlled_access',
    elementType: 'geometry',
    stylers: [{ color: '#4e4e4e' }],
  },
  {
    featureType: 'road.local',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#616161' }],
  },
  {
    featureType: 'transit',
    elementType: 'geometry',
    stylers: [{ color: '#2f3948' }],
  },
  {
    featureType: 'transit.station',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#d59563' }],
  },
  {
    featureType: 'water',
    elementType: 'geometry',
    stylers: [{ color: '#000000' }],
  },
  {
    featureType: 'water',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#3d3d3d' }],
  },
],

    Primary: '#000',
    backgroundPrimary: '#d9eafa',
    Secondary: '#303030',
    bgSecondary: '#f6f6f6',
    Tertiary: '#8e6bbf',
    backgroundTertiary: '#f1e8f6',
    Success: '#006400',
    Warning: '#cc7e00',
    backgroundWarning: '#fcf4e6',
    Yellow: '#cca300',
    Danger: '#fc141f',
    Dark: '#262525',
    Black: '#000000',
    textBlack: '#626B77',
    Medium: '#8c8c8c',
    Light: '#303030',
    AppBgColor: '#000',
    Snow: '#e0e0e0',
    Blue: '#004279',
    TextBlue: '#0092FF',
    CancelRed: '#EB3B3B',
    LightGrey: '#999999',
    Lightest: '#a8a8a8',
    SpringBud: '#85cc00',
    LinkClr: '#2952b8',
    LinkBlue: '#afc5e6',
    statusBar: '#b8c5c7',
    LightSkyBlue: '#c8d8e6',
    GradiantLightRed: '#cc0000',
    GradiantDarkRed: '#cc0000',
    GradiantLightGreen: '#4d9e55',
    GradiantDarkGreen: '#52a85b',
    Green: '#23CE6B',
    backgroundGreen: '#e8f6ee',
    borderColor: '#999',
    lightBorderColor: '#E5EAF1',
    TextColor: '#fff',
    White: '#fff',
    buttonColor: '#004BAC',
    DeleteBackground: '#FFEFEF',
    DeleteContent: '#D50D2D',
    AlertBackground: '#000',
    AlertContent: '#FF9F00',
    SubmitBackground: '#78BDF6',
    SubmitContent: '#004BAC',
    SuccessBackground: '#E2FFE7',
    SuccessContent: '#43BF57',
    SoftPurpel: '#8870ff',
    CreditPoint: '#4caf50',
    Progress: '#00c7b5',
    Scanned: '#00c075',
    PendingBg: '#f4c8c8',
    Pending: '#ff7600',
    Reject: '#ff0000',
    BadgeSection: '#FF8BA0',
    primary100: '#eaddff',
    error50: '#dc362e',
  },
  // dark:{
  //   Primary: '#45abff',
  //   backgroundPrimary: '#d9eafa',
  //   Secondary: '#303030',
  //   bgSecondary: '#f6f6f6',
  //   Tertiary: '#b794f6',
  //   backgroundTertiary: '#f1e8f6',
  //   Success: '#008000',
  //   CreditPoint: '#4caf50',
  //   Warning: '#FFA200',
  //   backgroundWarning: '#fcf4e6',
  //   Yellow: '#fae102',
  //   Danger: '#fc141f',
  //   Dark: '#262525',
  //   Black: '#000000',
  //   textBlack: '#626B77',
  //   Medium: '#a6a6a6',
  //   Progress: '#00c7b5',
  //   Light: '#fff',
  //   AppBgColor: '#f8f8f8',
  //   Snow: '#f9f9f9',
  //   Blue: '#0061a5',
  //   themeColor: '#004CAC',
  //   TextBlue: '#0092FF',
  //   LightGrey: '#b5b5b5',
  //   Lightest: '#c7c7c7',
  //   SpringBud: '#ABFF00',
  //   LinkClr: '#3f78f0',
  //   LinkBlue: '#d4e9ff',
  //   statusBar: '#dce4e6',
  //   LightSkyBlue: '#e8f2ff',
  //   CancelRed: '#EB3B3B',
  //   GradiantLightRed: '#f52a2a',
  //   GradiantDarkRed: '#ff0808',
  //   GradiantLightGreen: '#63c76f',
  //   GradiantDarkGreen: '#52a85b',
  //   borderColor: '#ccc',
  //   Green: '#23CE6B',
  //   backgroundGreen: '#e8f6ee',
  //   lightBorderColor: '#d8d8d8',
  //   TextColor: '#000',
  //   White: '#fff',
  //   buttonColor: '#004BAC',
  //   DeleteBackground: '#FFEFEF',
  //   DeleteContent: '#D50D2D',
  //   AlertBackground: '#FFF7EA',
  //   AlertContent: '#FF9F00',
  //   SubmitBackground: '#78BDF6',
  //   SubmitContent: '#004BAC',
  //   SuccessBackground: '#E2FFE7',
  //   SuccessContent: '#43BF57',
  //   SoftPurpel: '#8870ff',
  //   Scanned: '#00c075',
  //   PendingBg: '#f4c8c8',
  //   Pending: '#ff7600',
  //   Reject: '#ff0000',
  //   BadgeSection: '#FF8886',
  // }
};

export default AppTheme;
